name: Trigger App Docker Build

on:
  push:
    branches:
      - dev_monster

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger App Build
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            https://api.github.com/repos/dataforgood/13_stop_cyberviolence/dispatches \
            -d '{"event_type": "chainlit_updated"}'
